### ISSUE TITLE
Angular 5 compatibility?

### ISSUE THREAD

**Issue by roni-frantchi** [joeljeske/karma-parallel#13]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Occasionally getting:
```
Cannot configure the test module when the test module has already been instantiated. Make sure you are not using `inject` before `TestBed.configureTestingModule`
```

* **Please tell us about your environment:**

- version: 0.2.5
- Browser: Chrome
- Language: TypeScript

I was able to get the project going with [karma-sharding](https://github.com/rschuft/karma-sharding) .
That being said, considering the pro of being able to move to Webpack I'm wish I could use `karma-parallel` instead.
I cannot recreate this in stackblitz, CLI seems to work fine... Any other information I can provide you with that might help narrow down the root cause?..

**Comment by joeljeske** [comment]
Interesting. I cannot reproduce this. 

My attempted repro steps: 

```
ng new test-app
cd test-app
npm i karma-parallel
# Add 'parallel' to the frameworks list
# Add the `require('karma-parallel')` to the plugins list
ng test --watch=false
# All complete sucessfully 
```

```
ng --version
```
Prints: 
```
Angular CLI: 1.7.4
Node: 8.9.0
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```


Do you have any additional information or could you reproduce in a repo that you can share?

**Comment by joeljeske** [comment]
Closing due to lack of reproduction steps and inactivity.
