### ISSUE TITLE
Safari does execute all tests for each shard

### ISSUE THREAD

**Issue by chrisguttandin** [joeljeske/karma-parallel#22]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

I want to report a bug that occurs in the current version of Safari. I discovered this package only today, which is why I can't really tell for how long it is already present. I assume it is related to Safari's restrictive handling of cookies. I noticed that Safari will always execute all tests. I figured out that the cookie never gets send when karma is issuing requests from inside of its iframe. I tried several things to get it working, but in the end I implemented a solution which doesn't use cookies anymore. Instead of replacing `%KARMA_SHARD_INFO%` with the information for only one shard I modified the code to replace it with the info for all shards. The client side script does then pick the relevant information based on the query param of the `parent.location.href`. Would you like me to open a pull request with these changes?

* **Please tell us about your environment:**

- version: 2.0.4
- Browser: [Safari 11.1.2]
- Language: [TypeScript with webpack]

**Comment by joeljeske** [comment]
Interesting. Thank you! Yes, I would love to see a PR that reliably works without cookies. I have felt that tagging each instance with a cookie can be a bit fragile and only works when each browser instance is sandboxed.

**Comment by chrisguttandin** [comment]
Ok, I've just created #23.
