### ISSUE TITLE
No support for Circle CI

### ISSUE THREAD

**Issue by akashkriplani25** [joeljeske/karma-parallel#40]
* **I'm submitting a ... **
  - feature request

* **Do you want to request a *feature* or report a *bug*?** feature

* **What is the current behavior?**

The karma-parallel package fails to execute on the Circle CI 2.0

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I am using the angular 7 project. Update your karma.conf.js file as per the karma-parallel documentation and then raise a PR and build your project using Circle CI. The parallelOptions.executors value should be > 1 (I took an example as 2)

* **What is the expected behavior?**

Should run the tests in parallel and reduce the build time

Looking for fixes/support for Circle CI

**Comment by akashkriplani25** [comment]
Closing this issue as it was the node --max_old_space_size=8096 that was causing the issue. Increased the value to 16192 and it worked!

**Comment by lucasklaassen** [comment]
@akashkriplani25 were you able to run this in circle-ci and utilize multiple containers or would just just run all in the same container?
