### ISSUE TITLE
callThrough is not a function

### ISSUE THREAD

**Issue by Frrede** [joeljeske/karma-parallel#6]
* **I'm submitting a ... **
  - [x] bug report

* **What is the current behavior?**
When I use karma-parallel (in an angular 5 project) I get the error `callThrough is not a function` when running karma with code coverage.
This is because lodash version 3.1 is used in my project and `_.rest` is returning an array there:
https://lodash.com/docs/3.10.1#rest
`_.rest` is used in reporter.js `const callThrough = _.rest((fnName, args) => { ...`

So I guess one have to define a lodash version >4 in karma-parallel package.json to ensure the correct lodash version?

**Comment by Frrede** [comment]
thank you, great plugin btw! =)

**Comment by joeljeske** [comment]
Thanks! Fixed in 0.2.2
